Category.create!([
  {name: "Music"},
  {name: "Lecture"},
  {name: "Meeting"},
  {name: "Memo"},
  {name: "Other"}
])
# Comment.create!([
#   {content: "Wes anderson tote bag celiac church-key cleanse banjo.", author_id: 4, recording_id: 32, parent_id: nil},
#   {content: "Franzen heirloom five dollar toast.", author_id: 2, recording_id: 21, parent_id: nil},
#   {content: "Chambray direct trade organic asymmetrical dreamcatcher food truck cardigan blog.", author_id: 4, recording_id: 17, parent_id: nil},
#   {content: "Banh mi aesthetic raw denim scenester 3 wolf moon ennui diy.", author_id: 2, recording_id: 28, parent_id: nil},
#   {content: "Godard pitchfork meh microdosing humblebrag.", author_id: 4, recording_id: 6, parent_id: nil},
#   {content: "Williamsburg mumblecore helvetica freegan cold-pressed.", author_id: 3, recording_id: 27, parent_id: nil},
#   {content: "Vhs organic skateboard bitters slow-carb celiac.", author_id: 3, recording_id: 28, parent_id: nil},
#   {content: "Twee sustainable bicycle rights five dollar toast before they sold out deep v tacos vegan.", author_id: 1, recording_id: 17, parent_id: nil},
#   {content: "Street pabst aesthetic single-origin coffee pour-over vice lo-fi vhs.", author_id: 2, recording_id: 29, parent_id: nil},
#   {content: "Authentic yolo brooklyn.", author_id: 4, recording_id: 2, parent_id: nil},
#   {content: "Church-key flexitarian paleo quinoa tote bag vhs.", author_id: 3, recording_id: 15, parent_id: nil},
#   {content: "Taxidermy schlitz beard cred distillery bitters messenger bag.", author_id: 4, recording_id: 11, parent_id: nil},
#   {content: "Portland occupy slow-carb.", author_id: 1, recording_id: 26, parent_id: nil},
#   {content: "Taxidermy messenger bag bicycle rights tilde put a bird on it actually small batch neutra.", author_id: 2, recording_id: 3, parent_id: nil},
#   {content: "Pinterest ennui kitsch normcore letterpress.", author_id: 5, recording_id: 29, parent_id: nil},
#   {content: "Portland locavore salvia kinfolk yr pickled.", author_id: 4, recording_id: 20, parent_id: nil},
#   {content: "Taxidermy yuccie hella blue bottle.", author_id: 1, recording_id: 30, parent_id: nil},
#   {content: "Austin gluten-free park.", author_id: 2, recording_id: 26, parent_id: nil},
#   {content: "Cronut waistcoat salvia tilde messenger bag distillery polaroid neutra.", author_id: 2, recording_id: 19, parent_id: nil},
#   {content: "Yr fap aesthetic loko lomo.", author_id: 2, recording_id: 12, parent_id: nil},
#   {content: "Ramps pabst diy put a bird on it heirloom taxidermy.", author_id: 2, recording_id: 1, parent_id: nil},
#   {content: "Brooklyn kickstarter plaid tacos cold-pressed.", author_id: 1, recording_id: 7, parent_id: nil},
#   {content: "Ethical small batch shabby chic blog ramps cornhole.", author_id: 1, recording_id: 1, parent_id: nil},
#   {content: "Retro kickstarter yr tacos.", author_id: 4, recording_id: 18, parent_id: nil},
#   {content: "Fashion axe organic occupy hella.", author_id: 2, recording_id: 30, parent_id: nil},
#   {content: "Diy ennui cleanse cliche portland park kogi cred.", author_id: 5, recording_id: 23, parent_id: nil},
#   {content: "Cardigan ethical portland twee fap.", author_id: 3, recording_id: 17, parent_id: nil},
#   {content: "Taxidermy master park trust fund small batch cronut.", author_id: 4, recording_id: 12, parent_id: nil},
#   {content: "Brooklyn fanny pack hoodie tote bag.", author_id: 4, recording_id: 2, parent_id: nil},
#   {content: "Etsy celiac deep v scenester seitan knausgaard thundercats.", author_id: 1, recording_id: 16, parent_id: nil},
#   {content: "Distillery neutra portland.", author_id: 5, recording_id: 7, parent_id: nil},
#   {content: "Mustache umami craft beer leggings.", author_id: 3, recording_id: 25, parent_id: nil},
#   {content: "Park lumbersexual crucifix celiac.", author_id: 5, recording_id: 17, parent_id: nil},
#   {content: "Brooklyn lomo tote bag kogi.", author_id: 3, recording_id: 7, parent_id: nil},
#   {content: "Actually bitters seitan fap.", author_id: 2, recording_id: 19, parent_id: nil},
#   {content: "Viral pinterest trust fund.", author_id: 1, recording_id: 26, parent_id: nil},
#   {content: "Yr chambray stumptown paleo.", author_id: 5, recording_id: 4, parent_id: nil},
#   {content: "Try-hard vinyl meh selvage lumbersexual keytar.", author_id: 2, recording_id: 11, parent_id: nil},
#   {content: "Drinking kale chips cronut fixie hoodie salvia.", author_id: 2, recording_id: 9, parent_id: nil},
#   {content: "Before they sold out poutine austin occupy.", author_id: 1, recording_id: 15, parent_id: nil},
#   {content: "Gluten-free ennui semiotics neutra art party helvetica cred.", author_id: 1, recording_id: 12, parent_id: nil},
#   {content: "Keffiyeh 3 wolf moon tousled selfies kale chips hashtag.", author_id: 4, recording_id: 17, parent_id: nil},
#   {content: "Helvetica mumblecore celiac offal selvage twee flexitarian.", author_id: 3, recording_id: 9, parent_id: nil},
#   {content: "Poutine before they sold out jean shorts tote bag.", author_id: 3, recording_id: 17, parent_id: nil},
#   {content: "Mumblecore microdosing photo booth lomo aesthetic bicycle rights chambray.", author_id: 4, recording_id: 31, parent_id: nil},
#   {content: "Slow-carb salvia swag ramps craft beer.", author_id: 2, recording_id: 22, parent_id: nil},
#   {content: "Hammock goth organic synth actually keffiyeh pork belly.", author_id: 2, recording_id: 15, parent_id: nil},
#   {content: "Literally wes anderson messenger bag mumblecore health.", author_id: 5, recording_id: 7, parent_id: nil},
#   {content: "Typewriter before they sold out meh.", author_id: 1, recording_id: 20, parent_id: nil},
#   {content: "Yr portland hoodie single-origin coffee typewriter.", author_id: 4, recording_id: 10, parent_id: nil},
#   {content: "Master shabby chic williamsburg fanny pack mixtape.", author_id: 4, recording_id: 5, parent_id: nil},
#   {content: "Blue bottle chicharrones chillwave.", author_id: 5, recording_id: 5, parent_id: nil},
#   {content: "Xoxo keytar yuccie.", author_id: 3, recording_id: 16, parent_id: nil},
#   {content: "Bitters meditation farm-to-table.", author_id: 5, recording_id: 6, parent_id: nil},
#   {content: "Tilde lomo seitan.", author_id: 1, recording_id: 20, parent_id: nil},
#   {content: "Keytar poutine portland.", author_id: 3, recording_id: 11, parent_id: nil},
#   {content: "Viral truffaut deep v yr carry.", author_id: 4, recording_id: 2, parent_id: nil},
#   {content: "Fap mustache tilde cleanse irony.", author_id: 1, recording_id: 28, parent_id: nil},
#   {content: "Ramps kitsch meh xoxo.", author_id: 5, recording_id: 17, parent_id: nil},
#   {content: "Park selfies 8-bit normcore bitters vice farm-to-table.", author_id: 4, recording_id: 34, parent_id: nil},
#   {content: "Cardigan kombucha waistcoat.", author_id: 2, recording_id: 4, parent_id: nil},
#   {content: "Cleanse paleo shoreditch photo booth mustache tofu.", author_id: 4, recording_id: 13, parent_id: nil},
#   {content: "Master fap lomo single-origin coffee keffiyeh cardigan yolo.", author_id: 1, recording_id: 9, parent_id: nil},
#   {content: "Literally fap vinegar diy chartreuse kombucha.", author_id: 5, recording_id: 8, parent_id: nil},
#   {content: "Lomo hammock fanny pack brooklyn portland dreamcatcher.", author_id: 5, recording_id: 17, parent_id: nil},
#   {content: "Chicharrones typewriter lomo readymade locavore.", author_id: 1, recording_id: 5, parent_id: nil},
#   {content: "Cred park tacos gluten-free goth.", author_id: 3, recording_id: 28, parent_id: nil},
#   {content: "Carry kombucha listicle mixtape pork belly goth viral sustainable.", author_id: 2, recording_id: 17, parent_id: nil},
#   {content: "Celiac kickstarter pabst waistcoat.", author_id: 2, recording_id: 17, parent_id: nil},
#   {content: "Salvia etsy waistcoat.", author_id: 4, recording_id: 21, parent_id: nil},
#   {content: "Humblebrag artisan green juice ugh iphone bushwick.", author_id: 2, recording_id: 1, parent_id: nil},
#   {content: "Pbr&b flannel vegan leggings.", author_id: 5, recording_id: 9, parent_id: nil},
#   {content: "Retro deep v tattooed.", author_id: 5, recording_id: 22, parent_id: nil},
#   {content: "90's poutine hella seitan.", author_id: 3, recording_id: 13, parent_id: nil},
#   {content: "Tofu hashtag microdosing waistcoat raw denim helvetica park.", author_id: 5, recording_id: 18, parent_id: nil},
#   {content: "Messenger bag narwhal flannel pitchfork neutra.", author_id: 1, recording_id: 25, parent_id: nil},
#   {content: "3 wolf moon wayfarers poutine microdosing kogi venmo direct trade.", author_id: 3, recording_id: 5, parent_id: nil},
#   {content: "Disrupt mustache franzen.", author_id: 3, recording_id: 22, parent_id: nil},
#   {content: "Lomo 3 wolf moon +1 gluten-free next level keffiyeh single-origin coffee.", author_id: 2, recording_id: 34, parent_id: nil},
#   {content: "Kombucha portland put a bird on it diy kale chips tote bag.", author_id: 5, recording_id: 16, parent_id: nil},
#   {content: "Wayfarers goth irony sriracha.", author_id: 3, recording_id: 15, parent_id: nil},
#   {content: "Cray banh mi fingerstache gentrify salvia.", author_id: 1, recording_id: 26, parent_id: nil},
#   {content: "Messenger bag typewriter squid fap health post-ironic mlkshk.", author_id: 5, recording_id: 24, parent_id: nil},
#   {content: "Yuccie organic diy viral 8-bit meh actually bicycle rights.", author_id: 4, recording_id: 7, parent_id: nil},
#   {content: "Street vegan distillery migas squid.", author_id: 1, recording_id: 13, parent_id: nil},
#   {content: "Loko tilde chambray retro cornhole brunch intelligentsia.", author_id: 5, recording_id: 32, parent_id: nil},
#   {content: "Typewriter deep v you probably haven't heard of them.", author_id: 2, recording_id: 6, parent_id: nil},
#   {content: "Locavore yuccie 3 wolf moon fingerstache listicle artisan brooklyn diy.", author_id: 3, recording_id: 26, parent_id: nil},
#   {content: "Pop-up selvage lumbersexual try-hard mlkshk.", author_id: 4, recording_id: 30, parent_id: nil},
#   {content: "Crucifix try-hard asymmetrical taxidermy sustainable banh mi pabst cold-pressed.", author_id: 5, recording_id: 22, parent_id: nil},
#   {content: "Xoxo blue bottle marfa semiotics diy tousled.", author_id: 3, recording_id: 24, parent_id: nil},
#   {content: "Cliche loko wayfarers whatever vinyl umami pickled.", author_id: 4, recording_id: 18, parent_id: nil},
#   {content: "Seitan williamsburg gentrify mumblecore tofu organic kinfolk shabby chic.", author_id: 4, recording_id: 3, parent_id: nil},
#   {content: "Gluten-free cray asymmetrical hammock leggings.", author_id: 3, recording_id: 7, parent_id: nil},
#   {content: "Franzen pbr&b tote bag food truck park banjo.", author_id: 3, recording_id: 12, parent_id: nil},
#   {content: "Fap normcore deep v.", author_id: 3, recording_id: 8, parent_id: nil},
#   {content: "Small batch echo plaid.", author_id: 1, recording_id: 1, parent_id: nil},
#   {content: "Vhs kombucha polaroid tousled scenester hammock umami mixtape.", author_id: 4, recording_id: 24, parent_id: nil},
#   {content: "Banh mi knausgaard plaid chartreuse.", author_id: 5, recording_id: 32, parent_id: nil},
#   {content: "Distillery keffiyeh thundercats kogi typewriter.", author_id: 3, recording_id: 1, parent_id: nil},
#   {content: "Fingerstache celiac plaid godard vegan cronut.", author_id: 5, recording_id: 9, parent_id: nil},
#   {content: "Offal keytar umami.", author_id: 1, recording_id: 13, parent_id: nil},
#   {content: "Tattooed normcore diy gastropub.", author_id: 4, recording_id: 9, parent_id: nil},
#   {content: "Direct trade disrupt yuccie bespoke.", author_id: 3, recording_id: 24, parent_id: nil},
#   {content: "Master jean shorts try-hard.", author_id: 5, recording_id: 10, parent_id: nil},
#   {content: "Cleanse paleo biodiesel next level bespoke franzen iphone.", author_id: 2, recording_id: 6, parent_id: nil},
#   {content: "Viral fap tote bag actually disrupt jean shorts trust fund small batch.", author_id: 5, recording_id: 13, parent_id: nil},
#   {content: "Beard butcher lumbersexual kickstarter.", author_id: 1, recording_id: 32, parent_id: nil},
#   {content: "Semiotics yr xoxo mixtape cornhole tilde.", author_id: 5, recording_id: 8, parent_id: nil},
#   {content: "Drinking offal xoxo.", author_id: 3, recording_id: 3, parent_id: nil},
#   {content: "Pork belly church-key single-origin coffee blue bottle.", author_id: 5, recording_id: 19, parent_id: nil},
#   {content: "Knausgaard distillery portland cleanse yr dreamcatcher tilde.", author_id: 4, recording_id: 34, parent_id: nil},
#   {content: "Narwhal leggings health cleanse hammock tumblr.", author_id: 2, recording_id: 2, parent_id: nil},
#   {content: "90's cronut dreamcatcher squid lomo umami brunch.", author_id: 5, recording_id: 12, parent_id: nil},
#   {content: "Yr lo-fi chambray.", author_id: 3, recording_id: 25, parent_id: nil},
#   {content: "Waistcoat organic chia authentic gastropub brunch yolo.", author_id: 1, recording_id: 19, parent_id: nil},
#   {content: "Jean shorts master brunch tattooed loko hoodie kogi.", author_id: 3, recording_id: 4, parent_id: nil},
#   {content: "Taxidermy artisan neutra.", author_id: 3, recording_id: 25, parent_id: nil},
#   {content: "Artisan mixtape whatever sriracha salvia bicycle rights.", author_id: 4, recording_id: 8, parent_id: nil},
#   {content: "Park actually heirloom jean shorts chicharrones chillwave.", author_id: 4, recording_id: 3, parent_id: nil},
#   {content: "You probably haven't heard of them everyday actually meh disrupt whatever roof vegan.", author_id: 2, recording_id: 16, parent_id: nil},
#   {content: "Church-key chicharrones biodiesel slow-carb truffaut intelligentsia disrupt.", author_id: 4, recording_id: 21, parent_id: nil},
#   {content: "Jean shorts hella disrupt you probably haven't heard of them fanny pack xoxo austin try-hard.", author_id: 3, recording_id: 19, parent_id: nil},
#   {content: "Synth green juice twee park listicle helvetica banjo salvia.", author_id: 2, recording_id: 22, parent_id: nil},
#   {content: "Kinfolk hella post-ironic xoxo chia.", author_id: 3, recording_id: 3, parent_id: nil},
#   {content: "Franzen cray godard truffaut cliche swag.", author_id: 3, recording_id: 17, parent_id: nil},
#   {content: "Fanny pack synth plaid xoxo.", author_id: 4, recording_id: 8, parent_id: nil},
#   {content: "Iphone humblebrag art party meh biodiesel.", author_id: 3, recording_id: 25, parent_id: nil},
#   {content: "Put a bird on it migas venmo.", author_id: 3, recording_id: 18, parent_id: nil},
#   {content: "Disrupt heirloom godard.", author_id: 2, recording_id: 15, parent_id: nil},
#   {content: "Mustache jean shorts heirloom listicle.", author_id: 1, recording_id: 24, parent_id: nil},
#   {content: "Synth etsy cornhole truffaut.", author_id: 1, recording_id: 10, parent_id: nil},
#   {content: "Cred cliche distillery.", author_id: 4, recording_id: 14, parent_id: nil},
#   {content: "Selfies hoodie narwhal +1 tumblr.", author_id: 3, recording_id: 12, parent_id: nil},
#   {content: "Put a bird on it dreamcatcher tacos health food truck scenester.", author_id: 4, recording_id: 30, parent_id: nil},
#   {content: "90's portland seitan raw denim photo booth.", author_id: 4, recording_id: 19, parent_id: nil},
#   {content: "Blue bottle goth austin lumbersexual pork belly hoodie selvage.", author_id: 3, recording_id: 8, parent_id: nil},
#   {content: "Artisan hashtag squid crucifix humblebrag.", author_id: 5, recording_id: 25, parent_id: nil},
#   {content: "Fashion axe tote bag actually semiotics.", author_id: 5, recording_id: 22, parent_id: nil},
#   {content: "Gastropub polaroid chillwave beard.", author_id: 4, recording_id: 34, parent_id: nil},
#   {content: "Meditation cardigan shabby chic 8-bit.", author_id: 5, recording_id: 25, parent_id: nil},
#   {content: "Slow-carb echo occupy distillery.", author_id: 2, recording_id: 27, parent_id: nil},
#   {content: "Vinegar lo-fi waistcoat.", author_id: 3, recording_id: 18, parent_id: nil},
#   {content: "Raw denim twee kale chips wolf.", author_id: 4, recording_id: 3, parent_id: nil},
#   {content: "Pinterest disrupt portland vice scenester banh mi.", author_id: 4, recording_id: 21, parent_id: nil},
#   {content: "Kogi tattooed portland.", author_id: 1, recording_id: 27, parent_id: nil},
#   {content: "Health bitters williamsburg locavore.", author_id: 4, recording_id: 25, parent_id: nil},
#   {content: "Yuccie health single-origin coffee drinking sriracha.", author_id: 2, recording_id: 32, parent_id: nil},
#   {content: "Art party yolo echo.", author_id: 4, recording_id: 5, parent_id: nil},
#   {content: "Craft beer cleanse fanny pack hella tilde.", author_id: 4, recording_id: 8, parent_id: nil},
#   {content: "Normcore meditation pop-up single-origin coffee.", author_id: 3, recording_id: 31, parent_id: nil},
#   {content: "Put a bird on it occupy sustainable.", author_id: 3, recording_id: 17, parent_id: nil},
#   {content: "Poutine migas leggings plaid occupy.", author_id: 5, recording_id: 14, parent_id: nil},
#   {content: "Fashion axe meditation meggings slow-carb vinegar neutra fanny pack.", author_id: 1, recording_id: 4, parent_id: nil},
#   {content: "Deep v artisan narwhal.", author_id: 2, recording_id: 2, parent_id: nil},
#   {content: "Synth pork belly salvia mixtape shoreditch skateboard kitsch cliche.", author_id: 4, recording_id: 20, parent_id: nil},
#   {content: "Park dreamcatcher lumbersexual cleanse tousled williamsburg leggings asymmetrical.", author_id: 3, recording_id: 5, parent_id: nil},
#   {content: "Schlitz wolf banh mi polaroid forage kinfolk chia roof.", author_id: 2, recording_id: 17, parent_id: nil},
#   {content: "Pug fap small batch pork belly.", author_id: 2, recording_id: 8, parent_id: nil},
#   {content: "Letterpress artisan migas occupy etsy.", author_id: 2, recording_id: 20, parent_id: nil},
#   {content: "Beard shabby chic twee tote bag kinfolk 3 wolf moon etsy.", author_id: 2, recording_id: 18, parent_id: nil},
#   {content: "Wayfarers tumblr bitters 3 wolf moon.", author_id: 1, recording_id: 9, parent_id: nil},
#   {content: "Sriracha mixtape bushwick.", author_id: 5, recording_id: 30, parent_id: nil},
#   {content: "Polaroid try-hard bitters intelligentsia vice everyday semiotics master.", author_id: 2, recording_id: 16, parent_id: nil},
#   {content: "Xoxo pug artisan.", author_id: 4, recording_id: 9, parent_id: nil},
#   {content: "Vinegar before they sold out schlitz flannel ennui 3 wolf moon.", author_id: 1, recording_id: 7, parent_id: nil},
#   {content: "Fanny pack asymmetrical pork belly five dollar toast small batch leggings.", author_id: 5, recording_id: 32, parent_id: nil},
#   {content: "Pop-up freegan locavore brooklyn ethical viral messenger bag pug.", author_id: 3, recording_id: 9, parent_id: nil},
#   {content: "Waistcoat you probably haven't heard of them slow-carb heirloom biodiesel cold-pressed keytar fingerstache.", author_id: 1, recording_id: 23, parent_id: nil},
#   {content: "Vinegar franzen everyday roof.", author_id: 5, recording_id: 3, parent_id: nil},
#   {content: "Hella park deep v 90's 8-bit roof normcore plaid.", author_id: 5, recording_id: 18, parent_id: nil},
#   {content: "Pour-over gastropub austin flannel etsy godard direct trade.", author_id: 3, recording_id: 31, parent_id: nil},
#   {content: "Squid single-origin coffee five dollar toast lo-fi ethical cardigan.", author_id: 1, recording_id: 26, parent_id: nil},
#   {content: "8-bit twee bitters.", author_id: 4, recording_id: 30, parent_id: nil},
#   {content: "Locavore blue bottle keffiyeh poutine sustainable offal.", author_id: 5, recording_id: 24, parent_id: nil},
#   {content: "Truffaut microdosing selvage artisan pug intelligentsia street fap.", author_id: 5, recording_id: 33, parent_id: nil}
# ])
# Favorite.create!([
#   {user_id: 3, recording_id: 5},
#   {user_id: 3, recording_id: 4},
#   {user_id: 3, recording_id: 16},
#   {user_id: 3, recording_id: 24},
#   {user_id: 3, recording_id: 32},
#   {user_id: 6, recording_id: 4},
#   {user_id: 6, recording_id: 5},
#   {user_id: 6, recording_id: 1},
#   {user_id: 1, recording_id: 4},
#   {user_id: 1, recording_id: 2},
#   {user_id: 1, recording_id: 8},
#   {user_id: 1, recording_id: 9},
#   {user_id: 2, recording_id: 4},
#   {user_id: 2, recording_id: 2},
#   {user_id: 4, recording_id: 16},
#   {user_id: 4, recording_id: 12},
#   {user_id: 4, recording_id: 15},
#   {user_id: 4, recording_id: 32},
#   {user_id: 4, recording_id: 23},
#   {user_id: 4, recording_id: 31},
#   {user_id: 4, recording_id: 28},
#   {user_id: 5, recording_id: 16},
#   {user_id: 5, recording_id: 15},
#   {user_id: 5, recording_id: 27},
#   {user_id: 5, recording_id: 31},
#   {user_id: 5, recording_id: 32},
#   {user_id: 5, recording_id: 28}
# ])
# Recording.create!([
#   {title:"Adele - Someone Like You LIVE", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790042/Adele_-_Someone_Like_You_Live_at_The_Royal_Albert_Hall_k5u7kh.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797717/adele.jpg", description:"Adele performing Someone Like You live at the Royal Albert Hall", uploader_id: 1, publicity:"public", category_id: 1},
#   {title:"Justin Bieber - Love Yourself LIVE", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790045/Justin_Bieber_-_Love_Yourself_Jingle_Bell_Ball_2015_z6tbsh.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797758/bieber.jpg", description:"Justin Bieber performing Love Yourself live at Jingle Bell Ball (2015)", uploader_id: 2, publicity:"public", category_id: 1},
#   {title:"Eminem performing Stan live", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790055/Eminem_-_Stan_Live_m9lj6u.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798333/eminem.jpg", description:"Eminem performing Stan at a live concert", uploader_id: 4, publicity:"public", category_id: 1},
#   {title:"Taylor Swift Live at New York City", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790059/Taylor_Swift_-_Begin_Again_Live_from_New_York_City_fuv6sr.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797773/taylor.jpg", description:"Taylor Swift performing Begin Again Live at New York City", uploader_id: 5, publicity:"public", category_id: 1},
#   {title:"Mozart Music Concerto", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790069/W.A._Mozart_Music_Concerto_Flute_and_Harp_K_299_-_1st_Movement_-_Beautiful_Live_Classical_Concert_yxfqvc.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797743/mozart.jpg", description:"Mozart Music Concerto: Flute and Harp - K299 1st Movement at Beautiful Live Classical Concert", uploader_id: 1, publicity:"public", category_id: 1},
#   {title:"LIVE Kendrick and Beyonce - Freedom", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790080/Beyonc%C3%A9_Kendrick_Lamar_-_Freedom_Live_at_MetLife_Stadium_xjjfu8.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797869/kendrick.jpg", description:"Beyonce and Kendrick Lamar performing Freedom live at the MetLife Stadium", uploader_id: 2, publicity:"public", category_id: 1},
#   {title:"Ariana Grande (live) - Christmas Chill", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790088/Ariana_Grande_-_Christmas_Chill_Live_at_Z100_s_Jingle_Ball_2016_Medley_xsz52j.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797814/ariana.jpg", description:"Ariana Grande performing Christmas Chill live at Jingle Ball 2016 Medley", uploader_id: 4, publicity:"public", category_id: 1},
#   {title:"Lindsey Stirling - Shatter Me (live)", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790093/Lindsey_Stirling__Shatter_Me__--_Live_at_the_Kennedy_Center_azmtyg.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797882/lindsey.jpg", description:"Lindsey Stirling performing Shatter Me live at the Kennedy Center", uploader_id: 5, publicity:"public", category_id: 1},
#   {title:"Sungha Jung - Payphone LIVE", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790093/Maroon_5_Payphone__-_Sungha_Jung_Live_pckv6x.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797840/sungha.jpg", description:"Sungha Jung performing Payphone by Maroon 5 at live concert", uploader_id: 1, publicity:"public", category_id: 1},
#   {title:"My Dearest (piano) LIVE", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790097/My_Dearest_-_piano_-_Live_in_Taipei_rhjhej.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797900/piano.jpg", description:"My Dearest piano live performance in Taipei", uploader_id: 2, publicity:"public", category_id: 1},
#   {title:"The Chainsmokers - Closer LIVE", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790099/The_Chainsmokers_-_Closer_Live_from_the_2016_MTV_VMAs_ft._Halsey_nfs2wr.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797798/chainsmokers.jpg", description:"The Chainsmokers performing Closer live from the 2016 MTV VMAs", uploader_id: 3, publicity:"public", category_id: 1},
#   {title:"Introduction to Physics", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795282/Physics_Lecture_-_1_-_Introduction_to_Physics_inrp3a.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798017/physics.jpg", description:"Physics Lecture 1: Introduction to Physics", uploader_id: 4, publicity:"public", category_id: 2},
#   {title:"What is Biology?", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795325/What_is_Biology_-_Part_1__Lecture_1.1_gmoonk.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798097/bio.jpg", description:"What is Biology? Part 1 of Introduction to Biology Lecture Series", uploader_id: 5, publicity:"public", category_id: 2},
#   {title:"Enthalpy", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795378/Thermodynamics_Enthalpy_Lecture_1_vwicju.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798084/thermo.jpg", description:"Thermodynamics lecture on Enthalpy", uploader_id: 1, publicity:"public", category_id: 2},
#   {title:"Game Design Lecture", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795436/Rob_Pardo_Blizzard_Game_Design_Lecture_MIT_2014_t8rfap.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798032/gamedesign.jpg", description:"Game design lecture by Rob Pardo from MIT. Based off Blizzard's games.", uploader_id: 2, publicity:"public", category_id: 2},
#   {title:"Arrays vs Linked Lists", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795453/Data_Structures__Arrays_vs_Linked_Lists_mmirpx.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798116/array.jpg", description:"Data Structures lecture on arrays vs linked lists", uploader_id: 4, publicity:"public", category_id: 2},
#   {title:"Intro to R Statistical Software", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795461/EAN_GIS08_Lecture__Introduction_to_R_Statistical_Software_cqtbqz.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798129/stats.png", description:"EAN GIS08 Lecture: Introduction to R Statistical Software", uploader_id: 5, publicity:"public", category_id: 2},
#   {title:"Introduction to Polar Coordinates", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795483/Math_202_Lecture_23_-_Introduction_to_Polar_Coordinates_b4dgdb.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797917/math.jpg", description:"Math 202 Lecture 23 - Introduction to Polar Coordinates", uploader_id: 1, publicity:"public", category_id: 2},
#   {title:"Intro to Psychology", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795534/Intro_to_Psychology_Lecture_1_ny1nr8.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798184/psychology.jpg", description:"Introduction to Psychology Lecture 1", uploader_id: 2, publicity:"public", category_id: 2},
#   {title:"Economics 1 Lecture", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795560/Economics_1_-_Lecture_1_tr5fwy.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798072/econ.jpg", description:"Economics 1 Lecture", uploader_id: 4, publicity:"public", category_id: 2},
#   {title:"Chemistry 1A Lecture", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796054/Chemistry_1A_-_Lecture_1_mp3_aqzr5d.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798196/chemistry.jpg", description:"The first lecture of the chemistry introductory course series", uploader_id: 5, publicity:"public", category_id: 2},
#   {title:"Introduction to Sociology", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481795527/Sociology_1_-_Lecture_4_rsguc7.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798160/sociology.jpg", description:"Sociology 1 Lecture #4", uploader_id: 3, publicity:"public", category_id: 2},
#   {title:"Jose Mourinho Press Conference", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796170/Jose_Mourinho_s_Post-Match_Press_Conference_-_Manchester_United_2-1_Crystal_Palace_pa49ef.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798757/mourinho.jpg", description:"Jose Mourinho post-match press conference: ManU vs. Crystal Palace", uploader_id: 1, publicity:"public", category_id: 3},
#   {title:"TED Talks - Roger Antonsen", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796274/Math_is_the_hidden_secret_to_understanding_the_world___Roger_Antonsen_gahfix.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798795/ted1.jpg", description:"Roger Antonsen talks about how math is the hidden secret to understanding the world", uploader_id: 2, publicity:"public", category_id: 3},
#   {title:"Apple Internal Meeting - Sept. 23", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796277/Apple_Confidential_-_Steve_Jobs_on__Think_Different__-_Internal_Meeting_Sept._23_1997_nzkons.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798810/apple_meeting.jpg", description:"Apple's internal meeting where Steve Jobs talks about thinking differently", uploader_id: 4, publicity:"public", category_id: 3},
#   {title:"Leonard Press Conference", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796284/Meyers_Leonard_New_Contract_Press_Conference_kqhtee.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798843/leonard.jpg", description:"Meyers Leonard's new contract press conference", uploader_id: 5, publicity:"public", category_id: 3},
#   {title:"TSM Press Conference", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796343/TSM_Press_Conference_NA_LCS_Summer_2016_Finals_qbwgyy.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798867/tsm.jpg", description:"TSM press conference on NA LCS 2016 finals", uploader_id: 1, publicity:"public", category_id: 3},
#   {title:"RSA Conference 2016", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796358/Louder_Than_Words_j6oibs.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798978/rsa.jpg", description:"RSA Conference 2016 on how actions speak louder than words", uploader_id: 2, publicity:"public", category_id: 3},
#   {title:"TED Talks - Tim Urban", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796385/Inside_the_mind_of_a_master_procrastinator___Tim_Urban_v2vop1.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798877/ted2.jpg", description:"Tim Urban talks about the inside mind of a master procrastinator", uploader_id: 4, publicity:"public", category_id: 3},
#   {title:"CJ McCollumn Press Conference", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796410/CJ_McCollum_Contract_Extension_Press_Conference_yj1yld.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798890/mccollum.jpg", description:"CJ McCollum talks about his contract extension in this press conference", uploader_id: 5, publicity:"public", category_id: 3},
#   {title:"Apple iPhone 6 Conference", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796431/Apple_Special_Event_2014_-_iPhone_6_iPhone_6_Plus_Introduction_sujtci.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798823/apple_conference.jpg", description:"Apple's Special Event for the iPhone 6 and iPhone 6 Plus Introduction", uploader_id: 1, publicity:"public", category_id: 3},
#   {title:"Donal Trump Interview", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796436/Full_Interview__Donald_Trump_Melania_Family_with_George_Stephanopoulos_yh7otb.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798916/trump.jpg", description:"Full interview of Donald Trump and Melania Family with George Stephanopoulos", uploader_id: 2, publicity:"public", category_id: 3},
#   {title:"Search Quality Meeting", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481796213/Search_Quality_Meeting__Spelling_for_Long_Queries_Annotated_svy1fj.mp3", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481798777/google.jpg", description:"Search Quality meeting at Google on spelling for long queries", uploader_id: 3, publicity:"private", category_id: 3},
#   {title:"Utaite", recording_url:"https://res.cloudinary.com/record-cloud/video/upload/v1481790066/favorite_utaite_rrfnui.wav", image_url:"https://res.cloudinary.com/record-cloud/image/upload/v1481797679/utaite.jpg", description:"Best", uploader_id: 6, publicity:"public", category_id: 1}
#   ])
User.create!([
  {username: "admin", email: "admin@record-cloud.com", password_digest: "$2a$10$wEJybja3eKcR08zwXirGV.p2Ne2f1FdAALDG.eY2A7lAotKGRsLZC", session_token: "Vfa07hzDHrjREqfQs9WjWA", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1481830502/hn9rjlxf4wrhed8fytaj.png"}
])
#
# {username: "tiger", email: "tiger@record-cloud.com", password_digest: "$2a$10$KOezoD9JSVM4ucO8OsI.KuliwtLogkzDyQpSU4k2P7Ybc59F2L2xC", session_token: "yjmTkfL7jm4EFtHsdv5eTw", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1478905191/ctt8afzurniyjtv9kffv.jpg"},
# {username: "faceless-man", email: "man@record-cloud.com", password_digest: "$2a$10$fWbqII3UGlF7AWxk158w8OPv4.X7v3uNgvYE4.ilkUajre7DSoKnS", session_token: "Tx9Kyz8A5IYdYffPnlpoyw", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1478905420/aqrb0lvyuqwxn7hht9tt.png"},
# {username: "guest", email: "guest@email.com", password_digest: "$2a$10$5RryZq32hOKaJo9FqATWXOMt10VolOtazoVqqJIFucr1KlqXcCvbq", session_token: "NZxEjHRopdpDRyIFY5cJRw", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1481700841/guest_profile.png"},
# {username: "cat", email: "cat@record-cloud.com", password_digest: "$2a$10$rltAqwmj.KsNg2nIHouZxuzXYf4A5oiGZAx77PrF07/.8hkLhnPo.", session_token: "i3DVdOvB79cF6cYF2wB35A", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1481700661/cat.png"},
# {username: "pikachu", email: "pikachu@record-cloud.com", password_digest: "$2a$10$KtYhyM8lBV4sRt.F8PTMQuCP/rvNDykz/UjIzB11XuNVpm0WKAVj2", session_token: "sCUbe3p8IgazwmOegA-N3g", image_url: "https://res.cloudinary.com/record-cloud/image/upload/v1478905337/pikachu.png"},
